yarn upgrade-interactive
@svgr/webpack needed to be updated to solve SVG errors after updating
babel/core:

    ERROR in ./src/app/static/images/zap.svg
    Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
    Error: Cannot find module '@babel/plugin-transform-react-constant-elements' from 'lightning/joule-extension'